name: frontend2
description: "Frontend for is lab"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  shared_preferences: ^2.3.3
  http: ^1.2.2
  latlong2: ^0.9.1
  flutter_map: ^7.0.2
  flutter_map_cancellable_tile_provider: ^3.0.2
  stomp_dart_client: ^2.1.0
  intl: ^0.20.1
  file_picker: ^8.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true
